# Create orders

POST http://localhost:3333/notes/1
Content-Type: application/json

{
	"title": "Criptografia de dados",
	"description": "Essa é uma nota de exemplo",
	"tags": ["node", "bcryptjs"],
	"links": ["link1" , "link2"]
}

###

# Delete orders

DELETE http://localhost:3333/notes/1

###

# Index orders

GET http://localhost:3333/notes
		?user_id=1
		&title
		&tags=node

###

# Show orders

GET http://localhost:3333/notes/1