@resource = notes
@contentType = application/json
@userId = 1
@noteId = 3

# Create orders
POST {{baseUrl}}/{{resource}}/{{userId}}
Content-Type: {{contentType}}

{
	"title": "Criptografia de dados",
	"description": "Essa é uma nota de exemplo",
	"tags": ["node", "bcryptjs"],
	"links": ["link1" , "link2"]
}

###

# Delete orders
DELETE {{baseUrl}}/{{resource}}/{{noteId}}

###

# Index orders
GET {{baseUrl}}/{{resource}}
		?user_id={{userId}}
		&title
		&tags=node

###

# Show orders
GET {{baseUrl}}/{{resource}}/{{noteId}}